name: Tour deploy.. ✈️
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/*'
  pull_request:
    types: [closed]
    branches:
      - 'main'
jobs:
  deploy:
    name: 'Deploy my applications'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Chekout my code..
        uses: actions/checkout@v3

      - name: Set QUEM checking..
        uses: docker/setup-buildx-action@v3

      - name: Set Up Docker BuildX tool
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/tour:${{github.sha}}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            sudo docker stop tour || true
            sudo docker rm tour || true
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/tour:${{github.sha}}
            sudo docker run --name tour -v uploads:/app/uploads -d -p 5000:3000 ${{secrets.DOCKER_USERNAME}}/tour:${{github.sha}}
            sudo docker image prune -f -a
