name: Tour deploy.. ✈️

on:
    push:
        branches:
            - 'main'
    pull_request:
        types: [closed]
        branches:
            - 'main'

jobs:
    deploy:
        name: 'Deploy my applications'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout my code..
              uses: actions/checkout@v3

            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SERVER_PRIVATE_KEY }}
                  script: |
                      cd /elbe
                      ./deploy.sh
