name: Tour deploy test.. ✈️
on:
    push:
        branches:
            - 'test'
    pull_request:
        types: [closed]
        branches:
            - 'test'
jobs:
    deploy:
        name: 'Deploy my applications'
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
        steps:
            - name: Chekout my code..
              uses: actions/checkout@v3

            - name: Set QUEM checking..
              uses: docker/setup-buildx-action@v3

            - name: Set Up Docker BuildX tool
              uses: docker/setup-buildx-action@v3

            - name: Login to docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{secrets.DOCKER_PASSWORD }}

            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{secrets.DOCKER_USERNAME}}/test-tour:${{github.sha}}

            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.SERVER_HOST}}
                  username: ${{secrets.SERVER_USERNAME}}
                  key: ${{ secrets.SERVER_PRIVATE_KEY }}
                  script: |
                      sudo docker stop test-tour || true
                      sudo docker rm test-tour || true
                      sudo docker pull ${{secrets.DOCKER_USERNAME}}/test-tour:${{github.sha}}
                      sudo docker run --name test-tour -v uploads:/app/uploads -d -p 5001:3000 ${{secrets.DOCKER_USERNAME}}/test-tour:${{github.sha}}
                      sudo docker image prune -f -a
